export const services =  {
    categories: ['All', 'UX', 'Product', 'Brand'],
    packages: [
        { id: 1, image: '/assets/img/Work/Work-gallery-1.jpg', title: 'SmartThings', category: 'UX', description: 'Samsung SmartThings Mobile App design for Android/iOS' },
        { id: 2, image: '/assets/img/Work/Work-gallery-2.jpg', title: 'SmartThings', category: 'UX', description: 'Samsung SmartThings Mobile App design for Android/iOS' },
        { id: 3, image: '/assets/img/Work/Work-gallery-3.jpg', title: 'SmartThings', category: 'UX', description: 'Samsung SmartThings Mobile App design for Android/iOS' },
        { id: 4, image: '/assets/img/Work/Work-gallery-4.jpg', title: 'SmartThings', category: 'UX', description: 'Samsung SmartThings Mobile App design for Android/iOS' },
        { id: 5, image: '/assets/img/Work/Work-gallery-5.jpg', title: 'NFL CTV', category: 'UX', description: 'NFL CTV App for OTT, concoles and smart TV' },
        { id: 6, image: '/assets/img/Work/Work-gallery-6.jpg', title: 'NFL CTV ', category: 'UX', description: 'NFL CTV App for OTT, concoles and smart TV' },
        { id: 7, image: '/assets/img/Work/Work-gallery-7.jpg', title: 'Samsung TV', category: 'UX', description: 'Samsung Smart TV UX Design' },
        { id: 8, image: '/assets/img/Work/Work-gallery-8.jpg', title: 'Samsung TV', category: 'UX', description: 'Samsung Smart TV UX Design' },
        { id: 9, image: '/assets/img/Work/Work-gallery-9.jpg', title: 'Samsung VL', category: 'Product', description: 'Samsung smart speaker industrial and interaction design' },
        { id: 10, image: '/assets/img/Work/Work-gallery-10.jpg', title: 'Samsung VL', category: 'Product', description: 'Samsung smart speaker industrial and interaction design' },
        { id: 11, image: '/assets/img/Work/Work-gallery-11.jpg', title: 'Samsung VL', category: 'Product', description: 'Samsung smart speaker industrial and interaction design' },
        { id: 12, image: '/assets/img/Work/Work-gallery-12.jpg', title: 'Samsung R7', category: 'Product', description: 'Samsung smart speaker industrial and interaction design' },
        { id: 13, image: '/assets/img/Work/Work-gallery-13.jpg', title: 'Samsung R6', category: 'Product', description: 'Samsung smart speaker industrial and interaction design' },
        { id: 14, image: '/assets/img/Work/Work-gallery-14.jpg', title: 'Samsung R6', category: 'Product', description: 'Samsung smart speaker industrial and interaction design' },
        { id: 15, image: '/assets/img/Work/Work-gallery-15.jpg', title: 'Samsung R7', category: 'Product', description: 'Samsung smart speaker industrial and interaction design' },
        { id: 16, image: '/assets/img/Work/Work-gallery-16.jpg', title: 'Samsung UHD', category: 'Product', description: 'Samsung UHD player industrial design' },
        { id: 17, image: '/assets/img/Work/Work-gallery-17.jpg', title: 'Apple iPod', category: 'Brand', description: 'Apple interactive takeover ad design' },
        { id: 18, image: '/assets/img/Work/Work-gallery-18.jpg', title: 'ESPN', category: 'Brand', description: 'ESPN TV spot' },
        { id: 19, image: '/assets/img/Work/Work-gallery-19.jpg', title: 'ESPN U', category: 'Brand', description: 'ESPN U TV spot' },
        { id: 20, image: '/assets/img/Work/Work-gallery-20.jpg', title: 'Honda', category: 'Brand', description: 'Honda microsite splash video' },
    ],
}